##
## NOT multistage, resulting bigger image
##

# syntax=docker/dockerfile:1

FROM golang:1.17-alpine
RUN apk add --no-cache git
WORKDIR /app

# copy source files
COPY . ./

# downloading go modules
RUN go mod download


# building binary artifact
RUN go build -o /my-golang-app

# running the binary artifact
CMD [ "/my-golang-app" ]
